class Annotation:
    def __init__(self):
        self.ID = None  #unique id
        self.name = None #usergiven Name
        self.address = None #address to the folder containing the annotations
        self.of = None #the related dataset object
        self.tag = None #user assigned
        self.desc = None #descriptoin autogenerated by the system
        self.comment  = None #user provided comment
        self.created_at = None #timestamp

        